// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { defineComponent, h, resolveComponent } from 'vue';

export default defineComponent({
  name: 'EmptyRoute',
  setup() {
    const RouterView = resolveComponent('RouterView')
    return () => h(RouterView, null);
  },
});
