// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { createWebHashHistory, createMemoryHistory, createWebHistory } from 'E:/Src/osproj/X/newlife-cube-vueui/node_modules/.pnpm/registry.npmmirror.com+@umijs+renderer-vue@4.0.53_xsxatmlnmmg5bcuv3xdnj6fj7y/node_modules/@umijs/renderer-vue';
import type { RouterHistory } from 'E:/Src/osproj/X/newlife-cube-vueui/node_modules/.pnpm/registry.npmmirror.com+@umijs+renderer-vue@4.0.53_xsxatmlnmmg5bcuv3xdnj6fj7y/node_modules/@umijs/renderer-vue';

let history: RouterHistory;
export function createHistory(opts: any) {
  if (opts.type === 'hash') {
    history = createWebHashHistory(opts.basename);
  } else if (opts.type === 'memory') {
    history = createMemoryHistory(opts.basename);
  } else {
    history = createWebHistory(opts.basename);
  }
  return history;
}

export { history };
