export default {
  // baseUrl: 'http://localhost:5000',
  baseUrl: 'http://81.69.253.197:8000',
  login: '/Admin/User/Login',
  getUserInfo: '/Admin/User/Info/',
  logout: '/Admin/User/Login',
  getMenu: '/Admin/Index/GetMenuTree',
  getEntityFields: '/GetEntityFields',
  getDataList: '/Index',
  getData: '/Edit',
  deleteById: '/Delete',
  add: '/Add',
  edit: '/Edit',
  getObject: '/Index',
  updateObject: '/Update',
}
